name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Build TypeScript
        run: npm run build

      - name: Verify dist folder
        run: test -d dist && echo "dist folder exists" || echo "dist folder missing"
